mkdir build_windows
cd build_windows
cmake .. -DCMAKE_INSTALL_PREFIX:PATH=static_build -DCMAKE_BUILD_TYPE=Release -DDAWN_FETCH_DEPENDENCIES=ON -DDAWN_BUILD_MONOLITHIC_LIBRARY=STATIC -DDAWN_ENABLE_VULKAN=ON -DDAWN_ENABLE_D3D12=ON -DDAWN_ENABLE_D3D11=OFF -DDAWN_BUILD_SAMPLES=OFF -DDAWN_USE_GLFW=OFF -DTINT_BUILD_GLSL_VALIDATOR=OFF -DTINT_BUILD_TESTS=OFF -DTINT_BUILD_CMD_TOOLS=OFF -DDAWN_ENABLE_INSTALL=ON -DTINT_ENABLE_INSTALL=ON
cmake --build . -j %NUMBER_OF_PROCESSORS%
cmake --install . --config Release